{% set name = "rouge" %}
{% set version = "2.2.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 9a6dfba66fd686449eff227fb5f938e0abfe6722a61c6bbb1f834d5b2654770a

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Rouge aims to a be a simple, easy-to-extend drop-in replacement for pygments.

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/rouge-ruby/{{ name }}

extra:
  recipe-maintainers:
    - sodre
