{% set name = "rouge" %}
{% set version = "3.10.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 1fb77d626871746e886fe3bc28812031950e01ac1753d2ef3c3b45fdd64e421e

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Lightweight and flexible library for writing command-line apps in Ruby.

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/rouge-ruby/{{ name }}

extra:
  recipe-maintainers:
    - sodre
