travis:
  secure:
    BINSTAR_TOKEN: JxHasqRSDxpF0zBUOKHAKd5I70GVuZKjLjAtgysnmiAmuraeQLJPjo5oUb8Jd1aayrNj3Az054dOOoxjDe0XCwNXx2O6P9ar9DU2MwB8Frj4Z/Y3/Vpn1Jy/2kJvYqD1yrESraCGrxnB4bXZkMOUHpYcNbbKrzeh7g0zo5T1ubaudUmhTkKrQTfcGlAPza5x0+zexmRhmdJDPbW1X450x/Dz1nmWZSmHBhwgAdrctZo2acqmXj0MOSZlFnoRpGiacW1ckmHxSJaz3DYGe7GhHTWiLqv3MxIIEOm0ZbjdMe4AAl3ojayp0Z/ejgxZd/RR6UqE9e5pxJ0wF4so9S4xgvYr0V8Qg2hu2+vySB5ZXTRK13PQXbKAH8LeE1uhK63IOlJU3cWSi7ixJko/2zQERSRh8Z8yyMssAExwJEFW7ugMOEN8xWpaGOSJZ1p21zK/VC1KwcEx9iJBlUj2edXdbvDgZG0feYQDYp2a1yMpSZRS+ePuvDXUNKUaz3qoANHlHZByhhonKQxsU/tNgLtkKqtesGPGC1WHUAGvLYG5xr2VXEUHD2UEiBtdsfL88Csev9ZAXVfiPrj6vu7TiEL7+BTt83a1oviTBvjGmvbKEU5iAEUlZuFcQr0XmZbSYqx3WXn47qwJ/qNoVcxlWLum85OlGZc4q15qQdNcN+Vb4uM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
